/**
 * Email Service for Elevizion Dashboard
 * Uses Postmark for transactional emails
 * 
 * Deliverability best practices:
 * - From: "Elevizion" <noreply@elevizion.nl> (no-reply for technical correctness)
 * - Reply-To: info@elevizion.nl (so customers can still reply)
 * - Multipart emails (HTML + plain text)
 * - Message-ID generated by Postmark
 * - Transactional stream for non-marketing emails
 * 
 * Required DNS records (configure in domain DNS):
 * - SPF: v=spf1 include:spf.mtasv.net ~all
 * - DKIM: Postmark provides the DKIM record
 * - DMARC: v=DMARC1; p=none; rua=mailto:dmarc@elevizion.nl
 */

import * as postmark from "postmark";
import { storage } from "./storage";

// ============================================================================
// CENTRAL EMAIL CONFIGURATION
// ============================================================================
// All emails use these settings for consistency and deliverability.
// From = noreply (technical sender), Reply-To = info (for customer responses)

const EMAIL_CONFIG = {
  fromName: "Elevizion",
  fromEmail: "noreply@elevizion.nl",    // Technical sender (no-reply)
  replyTo: "info@elevizion.nl",          // Where customers can reply
  messageStream: "outbound",             // Transactional stream
  contactEmail: "info@elevizion.nl",     // For display in footer
};

// Brand colors
const BRAND = {
  primary: "#1e3a5f",      // Dark blue
  secondary: "#f8a12f",    // Orange
  accent: "#10b981",       // Green (for CTAs)
  background: "#f6f7f9",   // Light gray
  white: "#ffffff",
  text: "#333333",
  muted: "#666666",
  border: "#e5e7eb",
};

// Logo URL - hosted publicly for email clients
const LOGO_URL = "https://elevizion.nl/branding/logo-email.png";

// ============================================================================
// BODY BLOCKS SYSTEM
// ============================================================================
// Structured content blocks for consistent email formatting

export type BodyBlock = 
  | { type: "paragraph"; content: string }
  | { type: "bullets"; items: string[] }
  | { type: "divider" }
  | { type: "infoCard"; rows: Array<{ label: string; value: string }> }
  | { type: "warning"; title?: string; content: string }
  | { type: "html"; content: string };

function renderBodyBlock(block: BodyBlock): string {
  switch (block.type) {
    case "paragraph":
      return `<p style="margin:0 0 16px 0;line-height:1.7;">${block.content}</p>`;
    
    case "bullets":
      const items = block.items.map(item => 
        `<li style="margin:6px 0;line-height:1.6;">${item}</li>`
      ).join("");
      return `<ul style="margin:0 0 16px 0;padding-left:24px;">${items}</ul>`;
    
    case "divider":
      return `<hr style="border:none;border-top:1px solid ${BRAND.border};margin:24px 0;" />`;
    
    case "infoCard":
      const rows = block.rows.map(row => `
        <tr style="border-bottom:1px solid ${BRAND.border};">
          <td style="padding:12px 16px;font-weight:600;color:#374151;width:35%;">${row.label}</td>
          <td style="padding:12px 16px;">${row.value}</td>
        </tr>
      `).join("");
      return `
        <table style="width:100%;border-collapse:collapse;margin:20px 0;background:#f9fafb;border-radius:6px;overflow:hidden;">
          ${rows}
        </table>
      `;
    
    case "warning":
      return `
        <div style="background:#fef3c7;padding:16px;border-radius:6px;margin:20px 0;border-left:4px solid #f59e0b;">
          ${block.title ? `<p style="margin:0 0 8px 0;font-weight:600;color:#92400e;">${block.title}</p>` : ""}
          <p style="margin:0;color:#92400e;">${block.content}</p>
        </div>
      `;
    
    case "html":
      return block.content;
    
    default:
      return "";
  }
}

function renderBodyBlocks(blocks: BodyBlock[]): string {
  return blocks.map(renderBodyBlock).join("");
}

function bodyBlocksToText(blocks: BodyBlock[]): string {
  return blocks.map(block => {
    switch (block.type) {
      case "paragraph":
        return stripHtml(block.content) + "\n";
      case "bullets":
        return block.items.map(item => `• ${stripHtml(item)}`).join("\n") + "\n";
      case "divider":
        return "-".repeat(40) + "\n";
      case "infoCard":
        return block.rows.map(row => `${row.label}: ${stripHtml(row.value)}`).join("\n") + "\n";
      case "warning":
        return `⚠️ ${block.title ? block.title + ": " : ""}${stripHtml(block.content)}\n`;
      case "html":
        return stripHtml(block.content) + "\n";
      default:
        return "";
    }
  }).join("\n");
}

function stripHtml(html: string): string {
  return html
    .replace(/<a[^>]*href="([^"]*)"[^>]*>(.*?)<\/a>/gi, "$2 ($1)")
    .replace(/<strong>(.*?)<\/strong>/gi, "*$1*")
    .replace(/<b>(.*?)<\/b>/gi, "*$1*")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&euro;/g, "€")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .trim();
}

// ============================================================================
// CENTRAL EMAIL TEMPLATE WRAPPER
// ============================================================================

interface CompanyInfo {
  legalName: string;
  tradeName: string;
  email: string;
  website: string;
  kvkNumber?: string;
  vatNumber?: string;
}

const DEFAULT_COMPANY: CompanyInfo = {
  legalName: "Douven Services",
  tradeName: "Elevizion",
  email: "info@elevizion.nl",
  website: "elevizion.nl",
  kvkNumber: "90982541",
  vatNumber: "NL004857473B37",
};

interface EmailTemplateOptions {
  subject: string;
  preheader?: string;
  title?: string;
  introText?: string;
  bodyBlocks?: BodyBlock[];
  bodyHtml?: string;  // Legacy support - use bodyBlocks for new emails
  cta?: { label: string; url: string };
  secondaryCta?: { label: string; url: string };
  footerNote?: string;
  showUnsubscribe?: boolean;
  company?: CompanyInfo;
}

interface EmailTemplateResult {
  html: string;
  text: string;
}

export function baseEmailTemplate(options: EmailTemplateOptions): EmailTemplateResult {
  const { subject, preheader, title, introText, bodyBlocks, bodyHtml, cta, secondaryCta, footerNote, showUnsubscribe, company = DEFAULT_COMPANY } = options;
  const year = new Date().getFullYear();
  
  // Build content from either bodyBlocks (preferred) or legacy bodyHtml
  let contentHtml = "";
  if (introText) {
    contentHtml += `<p style="margin:0 0 16px 0;line-height:1.7;">${introText}</p>`;
  }
  if (bodyBlocks && bodyBlocks.length > 0) {
    contentHtml += renderBodyBlocks(bodyBlocks);
  } else if (bodyHtml) {
    contentHtml += bodyHtml;
  }
  
  // Preheader (hidden preview text for email clients)
  const preheaderHtml = preheader 
    ? `<div style="display:none;font-size:1px;color:#f6f7f9;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">${preheader}${"&nbsp;".repeat(100)}</div>`
    : "";

  // CTA button HTML
  const ctaHtml = cta ? `
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" style="margin: 28px 0;">
      <tr>
        <td align="left">
          <a href="${cta.url}" target="_blank" style="display:inline-block;padding:14px 32px;background-color:${BRAND.accent};color:#ffffff;text-decoration:none;font-weight:600;font-size:16px;border-radius:6px;text-align:center;">
            ${cta.label}
          </a>
        </td>
      </tr>
    </table>
    <p style="margin:0 0 20px 0;font-size:13px;color:${BRAND.muted};">
      Als de knop niet werkt, kopieer en plak deze link in je browser:<br>
      <a href="${cta.url}" style="color:${BRAND.primary};word-break:break-all;">${cta.url}</a>
    </p>
  ` : "";

  // Footer note
  const footerNoteHtml = footerNote 
    ? `<p style="margin:15px 0 0 0;font-size:12px;color:${BRAND.muted};font-style:italic;">${footerNote}</p>`
    : "";

  // Unsubscribe link (for marketing emails)
  const unsubscribeHtml = showUnsubscribe
    ? `<p style="margin:15px 0 0 0;"><a href="mailto:info@elevizion.nl?subject=Uitschrijven" style="color:${BRAND.muted};font-size:11px;">Uitschrijven van deze e-mails</a></p>`
    : "";

  const html = `
<!DOCTYPE html>
<html lang="nl" xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="x-apple-disable-message-reformatting">
  <title>${subject}</title>
  <!--[if mso]>
  <style type="text/css">
    table { border-collapse: collapse; }
    td { padding: 0; }
  </style>
  <![endif]-->
</head>
<body style="margin:0;padding:0;background-color:${BRAND.background};font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;-webkit-font-smoothing:antialiased;">
  ${preheaderHtml}
  
  <!-- Outer container -->
  <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color:${BRAND.background};">
    <tr>
      <td align="center" style="padding:40px 20px;">
        
        <!-- Email container -->
        <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="600" style="max-width:600px;background-color:${BRAND.white};border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">
          
          <!-- Header with logo -->
          <tr>
            <td style="padding:28px 40px;border-bottom:1px solid ${BRAND.border};">
              <img src="${LOGO_URL}" alt="Elevizion" width="160" style="display:block;max-width:160px;height:auto;" />
            </td>
          </tr>
          
          <!-- Main content -->
          <tr>
            <td style="padding:40px 40px 32px 40px;">
              ${title ? `<h1 style="margin:0 0 24px 0;font-size:24px;font-weight:600;color:${BRAND.primary};line-height:1.3;">${title}</h1>` : ""}
              
              <div style="font-size:15px;line-height:1.7;color:${BRAND.text};">
                ${contentHtml}
              </div>
              
              ${ctaHtml}
              ${secondaryCta ? `<p style="margin:0;font-size:14px;"><a href="${secondaryCta.url}" style="color:${BRAND.primary};text-decoration:underline;">${secondaryCta.label}</a></p>` : ""}
            </td>
          </tr>
          
          <!-- Footer -->
          <tr>
            <td style="padding:24px 40px;background-color:${BRAND.background};border-top:1px solid ${BRAND.border};">
              <p style="margin:0 0 8px 0;font-size:13px;color:${BRAND.muted};">
                Met vriendelijke groet,<br>
                <strong style="color:${BRAND.primary};">Team ${company.tradeName}</strong>
              </p>
              <p style="margin:12px 0 0 0;font-size:12px;color:${BRAND.muted};">
                ${company.legalName} &bull; ${company.email} &bull; ${company.website}
              </p>
              ${company.kvkNumber ? `<p style="margin:4px 0 0 0;font-size:11px;color:${BRAND.muted};">KvK: ${company.kvkNumber}${company.vatNumber ? ` &bull; BTW: ${company.vatNumber}` : ""}</p>` : ""}
              ${footerNoteHtml}
              ${unsubscribeHtml}
            </td>
          </tr>
          
        </table>
        
        <!-- Copyright -->
        <p style="margin:24px 0 0 0;font-size:11px;color:${BRAND.muted};text-align:center;">
          &copy; ${year} ${company.legalName}. Alle rechten voorbehouden.
        </p>
        
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();

  // Generate plain text version
  const text = generatePlainTextFromTemplate(options);

  return { html, text };
}

function generatePlainTextFromTemplate(options: EmailTemplateOptions): string {
  const { title, introText, bodyBlocks, bodyHtml, cta, secondaryCta, footerNote, company = DEFAULT_COMPANY } = options;
  const year = new Date().getFullYear();
  
  let text = "";
  
  if (title) {
    text += `${title}\n${"=".repeat(title.length)}\n\n`;
  }
  
  // Add intro text
  if (introText) {
    text += stripHtml(introText) + "\n\n";
  }
  
  // Convert bodyBlocks to text if available, otherwise use bodyHtml
  if (bodyBlocks && bodyBlocks.length > 0) {
    text += bodyBlocksToText(bodyBlocks);
  } else if (bodyHtml) {
    const bodyText = bodyHtml
      .replace(/<h[1-6][^>]*>(.*?)<\/h[1-6]>/gi, "\n$1\n" + "=".repeat(30) + "\n")
      .replace(/<p[^>]*>(.*?)<\/p>/gi, "$1\n\n")
      .replace(/<br\s*\/?>/gi, "\n")
      .replace(/<a[^>]*href="([^"]*)"[^>]*>(.*?)<\/a>/gi, "$2 ($1)")
      .replace(/<strong>(.*?)<\/strong>/gi, "*$1*")
      .replace(/<b>(.*?)<\/b>/gi, "*$1*")
      .replace(/<li[^>]*>(.*?)<\/li>/gi, "• $1\n")
      .replace(/<ul[^>]*>/gi, "\n")
      .replace(/<\/ul>/gi, "\n")
      .replace(/<[^>]+>/g, "")
      .replace(/&nbsp;/g, " ")
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&euro;/g, "€")
      .replace(/\n{3,}/g, "\n\n")
      .trim();
    text += bodyText;
  }
  
  if (cta) {
    text += `\n\n${cta.label}: ${cta.url}`;
  }
  
  if (secondaryCta) {
    text += `\n${secondaryCta.label}: ${secondaryCta.url}`;
  }
  
  text += "\n\n" + "-".repeat(40);
  text += "\nMet vriendelijke groet,";
  text += `\nTeam ${company.tradeName}`;
  text += `\n\n${company.legalName} | ${company.email} | ${company.website}`;
  if (company.kvkNumber) {
    text += `\nKvK: ${company.kvkNumber}${company.vatNumber ? ` | BTW: ${company.vatNumber}` : ""}`;
  }
  
  if (footerNote) {
    text += `\n\n${footerNote}`;
  }
  
  text += `\n\n© ${year} ${company.legalName}. Alle rechten voorbehouden.`;
  
  return text;
}

interface EmailConfig {
  to: string;
  subject: string;
  html: string;
  text?: string;
  // Optional overrides (normally not used for consistency)
  from?: string;
  fromName?: string;
  // For logging
  templateKey?: string;
  entityType?: string;
  entityId?: string;
  // Marketing emails need List-Unsubscribe header
  isMarketing?: boolean;
  unsubscribeUrl?: string;
}

interface EmailResult {
  success: boolean;
  message: string;
  messageId?: string;
  logId?: string;
}

// Check if Postmark is configured
export function isEmailConfigured(): boolean {
  return !!process.env.POSTMARK_SERVER_TOKEN;
}

// Get email configuration info (for health check and settings page)
export function getEmailConfig() {
  return {
    hasToken: !!process.env.POSTMARK_SERVER_TOKEN,
    fromAddress: `${EMAIL_CONFIG.fromName} <${EMAIL_CONFIG.fromEmail}>`,
    replyToAddress: EMAIL_CONFIG.replyTo,
    provider: "Postmark",
    domain: "elevizion.nl",
    messageStream: EMAIL_CONFIG.messageStream,
  };
}

// Deliverability DNS records information (for settings page)
export function getDeliverabilityInfo() {
  return {
    spf: {
      record: "v=spf1 include:spf.mtasv.net ~all",
      status: "configured",
      description: "Authoriseert Postmark om namens jouw domein te verzenden",
    },
    dkim: {
      record: "Zie Postmark dashboard voor DKIM record",
      status: "configured",
      description: "Digitale handtekening voor e-mail authenticatie",
    },
    dmarc: {
      record: "v=DMARC1; p=none; rua=mailto:dmarc@elevizion.nl",
      status: "warning",
      description: "Beschermt tegen e-mail spoofing (aanbevolen)",
    },
    returnPath: {
      record: "pm-bounces.elevizion.nl",
      status: "warning", 
      description: "Voor betere bounce handling (aanbevolen)",
    },
  };
}

// ============================================================================
// SHARED EMAIL BUILDER
// ============================================================================
// Single source of truth for building email HTML - used by both send and preview

export interface BuildEmailOptions {
  subject: string;
  bodyText: string;  // Raw template body text (will be converted to HTML)
  contactName?: string;  // For personalized intro
}

export function buildEmailHtml(options: BuildEmailOptions): { html: string; text: string } {
  const { subject, bodyText, contactName = "klant" } = options;
  
  // Always convert text to HTML for consistent rendering
  const bodyHtml = textToHtml(bodyText);
  
  return baseEmailTemplate({
    subject,
    preheader: bodyText.substring(0, 100),
    title: subject,
    introText: `Beste ${contactName},`,
    bodyBlocks: [{ type: "html", content: bodyHtml }],
    footerNote: "Met vriendelijke groet, Team Elevizion",
  });
}

export function textToHtml(text: string): string {
  if (!text) return "";
  const escaped = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  const paragraphs = escaped.split(/\n\n+/);
  return paragraphs.map(p => {
    const withBreaks = p.replace(/\n/g, "<br>");
    return `<p style="margin:0 0 16px 0;line-height:1.7;">${withBreaks}</p>`;
  }).join("");
}

export function isHtmlContent(content: string): boolean {
  return /<[a-z][\s\S]*>/i.test(content);
}

// Auto-generate plain text from HTML if not provided
function htmlToPlainText(html: string): string {
  return html
    .replace(/<h[1-6][^>]*>(.*?)<\/h[1-6]>/gi, "\n$1\n" + "-".repeat(30) + "\n")
    .replace(/<p[^>]*>(.*?)<\/p>/gi, "$1\n")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<a[^>]*href="([^"]*)"[^>]*>(.*?)<\/a>/gi, "$2 ($1)")
    .replace(/<strong>(.*?)<\/strong>/gi, "*$1*")
    .replace(/<li[^>]*>(.*?)<\/li>/gi, "• $1\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

// Send email via Postmark with optional logging
export async function sendEmail(config: EmailConfig): Promise<EmailResult> {
  const serverToken = process.env.POSTMARK_SERVER_TOKEN;
  
  if (!serverToken) {
    return {
      success: false,
      message: "Postmark is niet geconfigureerd. Voeg POSTMARK_SERVER_TOKEN toe aan environment variables."
    };
  }

  // Use consistent From/Reply-To (never random addresses)
  const fromAddress = `${EMAIL_CONFIG.fromName} <${EMAIL_CONFIG.fromEmail}>`;
  const replyTo = EMAIL_CONFIG.replyTo;

  // Auto-generate plain text if not provided
  const textBody = config.text || htmlToPlainText(config.html);

  // Create log entry if templateKey provided
  let logId: string | undefined;
  if (config.templateKey) {
    try {
      const log = await storage.createEmailLog({
        toEmail: config.to,
        templateKey: config.templateKey,
        entityType: config.entityType || null,
        entityId: config.entityId || null,
        status: "queued",
      });
      logId = log.id;
    } catch (err) {
      console.error("Failed to create email log:", err);
    }
  }

  try {
    const client = new postmark.ServerClient(serverToken);
    
    // Build email options
    const emailOptions: postmark.Models.Message = {
      From: fromAddress,
      To: config.to,
      Subject: config.subject,
      HtmlBody: config.html,
      TextBody: textBody,
      ReplyTo: replyTo,
      MessageStream: EMAIL_CONFIG.messageStream,
    };

    // Add List-Unsubscribe header for marketing emails
    if (config.isMarketing && config.unsubscribeUrl) {
      emailOptions.Headers = [
        { Name: "List-Unsubscribe", Value: `<${config.unsubscribeUrl}>` },
        { Name: "List-Unsubscribe-Post", Value: "List-Unsubscribe=One-Click" },
      ];
    }
    
    const result = await client.sendEmail(emailOptions);

    // Update log on success
    if (logId) {
      await storage.updateEmailLog(logId, {
        status: "sent",
        providerMessageId: result.MessageID,
        sentAt: new Date(),
      });
    }

    return {
      success: true,
      message: "E-mail succesvol verzonden",
      messageId: result.MessageID,
      logId,
    };
  } catch (error: any) {
    console.error("Postmark error:", error);
    
    // Update log on failure
    if (logId) {
      await storage.updateEmailLog(logId, {
        status: "failed",
        errorMessage: error.message,
      });
    }

    return {
      success: false,
      message: `Fout bij verzenden: ${error.message}`,
      logId,
    };
  }
}

// ============================================================================
// EMAIL TEMPLATES
// ============================================================================

interface ContractEmailData {
  advertiserName: string;
  contactName: string;
  contractName: string;
  monthlyPrice: string;
  vatPercent: string;
  startDate: string;
  endDate?: string | null;
  billingCycle: string;
  screens: string[];
}

export function generateContractEmail(data: ContractEmailData): EmailTemplateResult {
  const billingCycleNL = {
    monthly: "Maandelijks",
    quarterly: "Per Kwartaal", 
    yearly: "Jaarlijks",
  }[data.billingCycle] || data.billingCycle;

  const screensHtml = data.screens.length > 0 
    ? `<ul style="margin:12px 0;padding-left:20px;">${data.screens.map(s => `<li style="margin:4px 0;">${s}</li>`).join("")}</ul>`
    : "<p style=\"color:#666;\">Nog geen schermen toegewezen</p>";

  const bodyHtml = `
    <p>Beste ${data.contactName},</p>
    
    <p>Hartelijk dank voor uw vertrouwen in Elevizion. Hieronder vindt u de details van uw nieuwe reclamecontract:</p>
    
    <table style="width:100%;border-collapse:collapse;margin:20px 0;background:#f9fafb;border-radius:6px;overflow:hidden;">
      <tr style="border-bottom:1px solid #e5e7eb;">
        <td style="padding:12px 16px;font-weight:600;color:#374151;width:40%;">Bedrijf</td>
        <td style="padding:12px 16px;">${data.advertiserName}</td>
      </tr>
      <tr style="border-bottom:1px solid #e5e7eb;">
        <td style="padding:12px 16px;font-weight:600;color:#374151;">Contract</td>
        <td style="padding:12px 16px;">${data.contractName}</td>
      </tr>
      <tr style="border-bottom:1px solid #e5e7eb;">
        <td style="padding:12px 16px;font-weight:600;color:#374151;">Maandprijs</td>
        <td style="padding:12px 16px;">&euro;${data.monthlyPrice} <span style="color:#666;">(excl. ${data.vatPercent}% BTW)</span></td>
      </tr>
      <tr style="border-bottom:1px solid #e5e7eb;">
        <td style="padding:12px 16px;font-weight:600;color:#374151;">Facturatie</td>
        <td style="padding:12px 16px;">${billingCycleNL}</td>
      </tr>
      <tr style="border-bottom:1px solid #e5e7eb;">
        <td style="padding:12px 16px;font-weight:600;color:#374151;">Startdatum</td>
        <td style="padding:12px 16px;">${data.startDate}</td>
      </tr>
      <tr>
        <td style="padding:12px 16px;font-weight:600;color:#374151;">Einddatum</td>
        <td style="padding:12px 16px;">${data.endDate || "Doorlopend"}</td>
      </tr>
    </table>
    
    <p style="font-weight:600;margin:24px 0 8px 0;">Toegewezen Schermen</p>
    ${screensHtml}
    
    <p style="margin-top:24px;">Heeft u vragen over uw contract? Neem gerust contact met ons op.</p>
  `;

  return baseEmailTemplate({
    subject: `Uw Elevizion Contract: ${data.contractName}`,
    preheader: `Welkom bij Elevizion! Uw contract ${data.contractName} is bevestigd.`,
    title: "Welkom bij Elevizion!",
    bodyHtml,
    footerNote: "U ontvangt deze e-mail omdat u een reclamecontract heeft afgesloten bij Elevizion.",
  });
}

// Legacy function for backwards compatibility
export function generateContractEmailHtml(data: ContractEmailData): string {
  return generateContractEmail(data).html;
}

interface SepaEmailData {
  advertiserName: string;
  contactName: string;
  email: string;
  monthlyAmount: string;
  vatPercent: string;
  iban?: string;
  mandateReference?: string;
}

export function generateSepaEmail(data: SepaEmailData): EmailTemplateResult {
  const mandateRef = data.mandateReference || `ELV-${Date.now()}`;
  
  const bodyHtml = `
    <p>Beste ${data.contactName},</p>
    
    <p>Om de maandelijkse betalingen voor uw reclamecontract automatisch te verwerken, hebben wij een SEPA incassomachtiging nodig.</p>
    
    <table style="width:100%;border-collapse:collapse;margin:20px 0;background:#f9fafb;border-radius:6px;overflow:hidden;">
      <tr style="border-bottom:1px solid #e5e7eb;">
        <td style="padding:12px 16px;font-weight:600;color:#374151;width:40%;">Incassant ID</td>
        <td style="padding:12px 16px;">NL00ZZZ000000000000</td>
      </tr>
      <tr style="border-bottom:1px solid #e5e7eb;">
        <td style="padding:12px 16px;font-weight:600;color:#374151;">Naam incassant</td>
        <td style="padding:12px 16px;">Elevizion B.V.</td>
      </tr>
      <tr style="border-bottom:1px solid #e5e7eb;">
        <td style="padding:12px 16px;font-weight:600;color:#374151;">Kenmerk machtiging</td>
        <td style="padding:12px 16px;">${mandateRef}</td>
      </tr>
      <tr style="border-bottom:1px solid #e5e7eb;">
        <td style="padding:12px 16px;font-weight:600;color:#374151;">Bedrijfsnaam</td>
        <td style="padding:12px 16px;">${data.advertiserName}</td>
      </tr>
      <tr>
        <td style="padding:12px 16px;font-weight:600;color:#374151;">Maandbedrag</td>
        <td style="padding:12px 16px;">&euro;${data.monthlyAmount} <span style="color:#666;">(incl. ${data.vatPercent}% BTW)</span></td>
      </tr>
    </table>
    
    <div style="background:#fef3c7;padding:16px;border-radius:6px;margin:20px 0;border-left:4px solid #f59e0b;">
      <p style="margin:0;font-weight:600;color:#92400e;">Actie vereist</p>
      <p style="margin:8px 0 0 0;color:#92400e;">Vul het bijgevoegde SEPA machtigingsformulier in en stuur het ondertekend retour naar <a href="mailto:administratie@elevizion.nl" style="color:#1e3a5f;">administratie@elevizion.nl</a></p>
    </div>
    
    <p style="font-size:13px;color:#666;">Door ondertekening van dit formulier machtigt u Elevizion B.V. doorlopend incasso-opdrachten te sturen naar uw bank om een bedrag van uw rekening af te schrijven overeenkomstig de opdracht van Elevizion B.V.</p>
    
    <p style="margin-top:24px;">Heeft u vragen? Neem gerust contact met ons op.</p>
  `;

  return baseEmailTemplate({
    subject: "SEPA Incassomachtiging - Elevizion",
    preheader: "Verzoek om SEPA incassomachtiging voor uw Elevizion contract",
    title: "SEPA Incassomachtiging",
    bodyHtml,
    footerNote: "U ontvangt deze e-mail omdat u een reclamecontract heeft afgesloten bij Elevizion.",
  });
}

// Legacy function for backwards compatibility
export function generateSepaEmailHtml(data: SepaEmailData): string {
  return generateSepaEmail(data).html;
}

// Send contract confirmation email
export async function sendContractEmail(
  toEmail: string,
  data: ContractEmailData
): Promise<EmailResult> {
  const { html, text } = generateContractEmail(data);
  return sendEmail({
    to: toEmail,
    subject: `Uw Elevizion Contract: ${data.contractName}`,
    html,
    text,
    templateKey: "contract_confirmation",
  });
}

// Send SEPA mandate request email
export async function sendSepaEmail(
  toEmail: string,
  data: SepaEmailData
): Promise<EmailResult> {
  const { html, text } = generateSepaEmail(data);
  return sendEmail({
    to: toEmail,
    subject: "SEPA Incassomachtiging - Elevizion",
    html,
    text,
    templateKey: "sepa_mandate_request",
  });
}
