/**
 * Email Service for Elevizion Dashboard
 * Uses Postmark for transactional emails
 * 
 * Deliverability best practices:
 * - Consistent From: "Elevizion" <info@elevizion.nl>
 * - Reply-To: info@elevizion.nl
 * - Multipart emails (HTML + plain text)
 * - Message-ID generated by Postmark
 * - Transactional stream for non-marketing emails
 * 
 * Required DNS records (configure in domain DNS):
 * - SPF: v=spf1 include:spf.mtasv.net ~all
 * - DKIM: Postmark provides the DKIM record
 * - DMARC: v=DMARC1; p=none; rua=mailto:dmarc@elevizion.nl
 */

import * as postmark from "postmark";
import { storage } from "./storage";

// Consistent sender configuration
const EMAIL_CONFIG = {
  fromName: "Elevizion",
  fromEmail: "info@elevizion.nl",
  replyTo: "info@elevizion.nl",
  messageStream: "outbound", // Transactional stream
};

interface EmailConfig {
  to: string;
  subject: string;
  html: string;
  text?: string;
  // Optional overrides (normally not used for consistency)
  from?: string;
  fromName?: string;
  // For logging
  templateKey?: string;
  entityType?: string;
  entityId?: string;
  // Marketing emails need List-Unsubscribe header
  isMarketing?: boolean;
  unsubscribeUrl?: string;
}

interface EmailResult {
  success: boolean;
  message: string;
  messageId?: string;
  logId?: string;
}

// Check if Postmark is configured
export function isEmailConfigured(): boolean {
  return !!process.env.POSTMARK_SERVER_TOKEN;
}

// Get email configuration info (for health check and settings page)
export function getEmailConfig() {
  return {
    hasToken: !!process.env.POSTMARK_SERVER_TOKEN,
    fromAddress: `${EMAIL_CONFIG.fromName} <${EMAIL_CONFIG.fromEmail}>`,
    replyToAddress: EMAIL_CONFIG.replyTo,
    provider: "Postmark",
    domain: "elevizion.nl",
    messageStream: EMAIL_CONFIG.messageStream,
  };
}

// Deliverability DNS records information (for settings page)
export function getDeliverabilityInfo() {
  return {
    spf: {
      record: "v=spf1 include:spf.mtasv.net ~all",
      status: "configured",
      description: "Authoriseert Postmark om namens jouw domein te verzenden",
    },
    dkim: {
      record: "Zie Postmark dashboard voor DKIM record",
      status: "configured",
      description: "Digitale handtekening voor e-mail authenticatie",
    },
    dmarc: {
      record: "v=DMARC1; p=none; rua=mailto:dmarc@elevizion.nl",
      status: "warning",
      description: "Beschermt tegen e-mail spoofing (aanbevolen)",
    },
    returnPath: {
      record: "pm-bounces.elevizion.nl",
      status: "warning", 
      description: "Voor betere bounce handling (aanbevolen)",
    },
  };
}

// Auto-generate plain text from HTML if not provided
function htmlToPlainText(html: string): string {
  return html
    .replace(/<h[1-6][^>]*>(.*?)<\/h[1-6]>/gi, "\n$1\n" + "-".repeat(30) + "\n")
    .replace(/<p[^>]*>(.*?)<\/p>/gi, "$1\n")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<a[^>]*href="([^"]*)"[^>]*>(.*?)<\/a>/gi, "$2 ($1)")
    .replace(/<strong>(.*?)<\/strong>/gi, "*$1*")
    .replace(/<li[^>]*>(.*?)<\/li>/gi, "• $1\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

// Send email via Postmark with optional logging
export async function sendEmail(config: EmailConfig): Promise<EmailResult> {
  const serverToken = process.env.POSTMARK_SERVER_TOKEN;
  
  if (!serverToken) {
    return {
      success: false,
      message: "Postmark is niet geconfigureerd. Voeg POSTMARK_SERVER_TOKEN toe aan environment variables."
    };
  }

  // Use consistent From/Reply-To (never random addresses)
  const fromAddress = `${EMAIL_CONFIG.fromName} <${EMAIL_CONFIG.fromEmail}>`;
  const replyTo = EMAIL_CONFIG.replyTo;

  // Auto-generate plain text if not provided
  const textBody = config.text || htmlToPlainText(config.html);

  // Create log entry if templateKey provided
  let logId: string | undefined;
  if (config.templateKey) {
    try {
      const log = await storage.createEmailLog({
        toEmail: config.to,
        templateKey: config.templateKey,
        entityType: config.entityType || null,
        entityId: config.entityId || null,
        status: "queued",
      });
      logId = log.id;
    } catch (err) {
      console.error("Failed to create email log:", err);
    }
  }

  try {
    const client = new postmark.ServerClient(serverToken);
    
    // Build email options
    const emailOptions: postmark.Models.Message = {
      From: fromAddress,
      To: config.to,
      Subject: config.subject,
      HtmlBody: config.html,
      TextBody: textBody,
      ReplyTo: replyTo,
      MessageStream: EMAIL_CONFIG.messageStream,
    };

    // Add List-Unsubscribe header for marketing emails
    if (config.isMarketing && config.unsubscribeUrl) {
      emailOptions.Headers = [
        { Name: "List-Unsubscribe", Value: `<${config.unsubscribeUrl}>` },
        { Name: "List-Unsubscribe-Post", Value: "List-Unsubscribe=One-Click" },
      ];
    }
    
    const result = await client.sendEmail(emailOptions);

    // Update log on success
    if (logId) {
      await storage.updateEmailLog(logId, {
        status: "sent",
        providerMessageId: result.MessageID,
        sentAt: new Date(),
      });
    }

    return {
      success: true,
      message: "E-mail succesvol verzonden",
      messageId: result.MessageID,
      logId,
    };
  } catch (error: any) {
    console.error("Postmark error:", error);
    
    // Update log on failure
    if (logId) {
      await storage.updateEmailLog(logId, {
        status: "failed",
        errorMessage: error.message,
      });
    }

    return {
      success: false,
      message: `Fout bij verzenden: ${error.message}`,
      logId,
    };
  }
}

// ============================================================================
// EMAIL TEMPLATES
// ============================================================================

interface ContractEmailData {
  advertiserName: string;
  contactName: string;
  contractName: string;
  monthlyPrice: string;
  vatPercent: string;
  startDate: string;
  endDate?: string | null;
  billingCycle: string;
  screens: string[];
}

export function generateContractEmailHtml(data: ContractEmailData): string {
  const billingCycleNL = {
    monthly: "Maandelijks",
    quarterly: "Per Kwartaal", 
    yearly: "Jaarlijks",
  }[data.billingCycle] || data.billingCycle;

  const screensHtml = data.screens.length > 0 
    ? `<ul>${data.screens.map(s => `<li>${s}</li>`).join("")}</ul>`
    : "<p>Nog geen schermen toegewezen</p>";

  return `
<!DOCTYPE html>
<html lang="nl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Nieuw Contract - Elevizion</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #1e3a5f 0%, #2d5a87 100%); padding: 30px; text-align: center; border-radius: 8px 8px 0 0;">
    <h1 style="color: white; margin: 0; font-size: 24px;">Elevizion</h1>
    <p style="color: #f8a12f; margin: 5px 0 0 0; font-size: 14px;">See Your Business Grow</p>
  </div>
  
  <div style="background: #f9f9f9; padding: 30px; border: 1px solid #ddd; border-top: none;">
    <h2 style="color: #1e3a5f; margin-top: 0;">Welkom bij Elevizion!</h2>
    
    <p>Beste ${data.contactName},</p>
    
    <p>Hartelijk dank voor uw vertrouwen in Elevizion. Hieronder vindt u de details van uw nieuwe reclamecontract:</p>
    
    <div style="background: white; padding: 20px; border-radius: 8px; border-left: 4px solid #f8a12f; margin: 20px 0;">
      <h3 style="color: #1e3a5f; margin-top: 0;">Contractgegevens</h3>
      <table style="width: 100%; border-collapse: collapse;">
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Bedrijf:</strong></td>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${data.advertiserName}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Contract:</strong></td>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${data.contractName}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Maandprijs:</strong></td>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;">€${data.monthlyPrice} (excl. ${data.vatPercent}% BTW)</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Facturatie:</strong></td>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${billingCycleNL}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Startdatum:</strong></td>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${data.startDate}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0;"><strong>Einddatum:</strong></td>
          <td style="padding: 8px 0;">${data.endDate || "Doorlopend"}</td>
        </tr>
      </table>
    </div>
    
    <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0;">
      <h3 style="color: #1e3a5f; margin-top: 0;">Toegewezen Schermen</h3>
      ${screensHtml}
    </div>
    
    <p style="margin-top: 30px;">Heeft u vragen over uw contract? Neem gerust contact met ons op.</p>
    
    <p>Met vriendelijke groet,<br><strong>Team Elevizion</strong></p>
  </div>
  
  <div style="text-align: center; padding: 20px; color: #666; font-size: 12px;">
    <p>© ${new Date().getFullYear()} Elevizion. Alle rechten voorbehouden.</p>
  </div>
</body>
</html>
  `;
}

interface SepaEmailData {
  advertiserName: string;
  contactName: string;
  email: string;
  monthlyAmount: string;
  vatPercent: string;
  iban?: string;
  mandateReference?: string;
}

export function generateSepaEmailHtml(data: SepaEmailData): string {
  const mandateRef = data.mandateReference || `ELV-${Date.now()}`;
  
  return `
<!DOCTYPE html>
<html lang="nl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SEPA Machtiging - Elevizion</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #1e3a5f 0%, #2d5a87 100%); padding: 30px; text-align: center; border-radius: 8px 8px 0 0;">
    <h1 style="color: white; margin: 0; font-size: 24px;">Elevizion</h1>
    <p style="color: #f8a12f; margin: 5px 0 0 0; font-size: 14px;">See Your Business Grow</p>
  </div>
  
  <div style="background: #f9f9f9; padding: 30px; border: 1px solid #ddd; border-top: none;">
    <h2 style="color: #1e3a5f; margin-top: 0;">SEPA Incassomachtiging</h2>
    
    <p>Beste ${data.contactName},</p>
    
    <p>Om de maandelijkse betalingen voor uw reclamecontract automatisch te verwerken, hebben wij een SEPA incassomachtiging nodig.</p>
    
    <div style="background: white; padding: 20px; border-radius: 8px; border-left: 4px solid #f8a12f; margin: 20px 0;">
      <h3 style="color: #1e3a5f; margin-top: 0;">Machtigingsgegevens</h3>
      <table style="width: 100%; border-collapse: collapse;">
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Incassant ID:</strong></td>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;">NL00ZZZ000000000000</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Naam incassant:</strong></td>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;">Elevizion B.V.</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Kenmerk machtiging:</strong></td>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${mandateRef}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Bedrijfsnaam:</strong></td>
          <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${data.advertiserName}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0;"><strong>Maandbedrag:</strong></td>
          <td style="padding: 8px 0;">€${data.monthlyAmount} (incl. ${data.vatPercent}% BTW)</td>
        </tr>
      </table>
    </div>
    
    <div style="background: #fff3cd; padding: 15px; border-radius: 8px; margin: 20px 0; border: 1px solid #ffc107;">
      <p style="margin: 0;"><strong>Actie vereist:</strong> Vul het bijgevoegde SEPA machtigingsformulier in en stuur het ondertekend retour naar <a href="mailto:administratie@elevizion.nl">administratie@elevizion.nl</a></p>
    </div>
    
    <p>Door ondertekening van dit formulier machtigt u Elevizion B.V. doorlopend incasso-opdrachten te sturen naar uw bank om een bedrag van uw rekening af te schrijven en aan uw bank om doorlopend een bedrag af te schrijven overeenkomstig de opdracht van Elevizion B.V.</p>
    
    <p style="margin-top: 30px;">Heeft u vragen? Neem gerust contact met ons op.</p>
    
    <p>Met vriendelijke groet,<br><strong>Team Elevizion</strong></p>
  </div>
  
  <div style="text-align: center; padding: 20px; color: #666; font-size: 12px;">
    <p>© ${new Date().getFullYear()} Elevizion. Alle rechten voorbehouden.</p>
  </div>
</body>
</html>
  `;
}

// Send contract confirmation email
export async function sendContractEmail(
  toEmail: string,
  data: ContractEmailData
): Promise<EmailResult> {
  return sendEmail({
    to: toEmail,
    subject: `Uw Elevizion Contract: ${data.contractName}`,
    html: generateContractEmailHtml(data),
  });
}

// Send SEPA mandate request email
export async function sendSepaEmail(
  toEmail: string,
  data: SepaEmailData
): Promise<EmailResult> {
  return sendEmail({
    to: toEmail,
    subject: "SEPA Incassomachtiging - Elevizion",
    html: generateSepaEmailHtml(data),
  });
}
